"""Tests for code_generator.py — auto-generated client code, detector name."""

from app.services.code_generator import TEM_CLIENT_CODE, DIGITAL_TWIN_TEMPLATE
from app.constants import DEFAULT_DETECTOR


class TestAutoGeneratedClientCode:
    def test_code_is_nonempty(self):
        assert isinstance(TEM_CLIENT_CODE, str)
        assert len(TEM_CLIENT_CODE) > 200

    def test_code_contains_stemclient_class(self):
        assert "class STEMClient" in TEM_CLIENT_CODE

    def test_code_contains_all_core_methods(self):
        required = [
            "def is_connected",
            "def get_detectors",
            "def get_detector_settings",
            "def device_settings",
            "def get_stage",
            "def set_stage",
            "def acquire_image",
            "def autofocus",
            "def get_command_log",
            "def clear_command_log",
        ]
        for method in required:
            assert method in TEM_CLIENT_CODE, f"Missing: {method}"

    def test_code_contains_extended_methods(self):
        extended = [
            "def set_mode",
            "def get_mode",
            "def set_beam",
            "def get_beam",
            "def set_tilt",
            "def get_tilt",
            "def set_sample_type",
            "def get_sample_type",
            "def set_diffraction_settings",
            "def get_diffraction_settings",
        ]
        for method in extended:
            assert method in TEM_CLIENT_CODE, f"Missing extended: {method}"

    def test_code_compiles(self):
        """The auto-generated code must be valid Python."""
        compile(TEM_CLIENT_CODE, "<tem_client>", "exec")


class TestDigitalTwinTemplate:
    def test_template_uses_correct_detector(self):
        assert "flu_camera" not in DIGITAL_TWIN_TEMPLATE
        assert DEFAULT_DETECTOR in DIGITAL_TWIN_TEMPLATE
