"""
Microscopy Code Generator

Generates Python automation scripts for the STEM Digital Twin. Scripts embed
ONLY MicroscopeControlClient — the portable control surface — so the same
script runs unmodified against a real instrument. Sample selection and
simulation environments happen in the GridScope UI before a run; they never
appear in generated code.
"""

import os
from typing import Optional
from openai import AsyncOpenAI
from ..models.schemas import ExperimentConfig, CodeGenerationRequest
from ..constants import (
    CONTROL_CLIENT_SOURCE_PATH,
    DEFAULT_DETECTOR,
    IMAGE_MARKER,
    MICROSCOPE_API_SPEC,
)


def _load_control_client_code() -> str:
    """Read control_client.py source at import time for embedding in scripts."""
    return CONTROL_CLIENT_SOURCE_PATH.read_text()


CONTROL_CLIENT_CODE = _load_control_client_code()


# Helper embedded in every script: streams acquired frames to the GridScope UI
# via the stdout marker protocol. Harmless when run outside GridScope (it just
# prints one long line).
REPORT_IMAGE_HELPER = f'''
def report_image(img, **meta):
    """Stream an acquired frame to the GridScope UI. Call after every acquire."""
    import base64 as _b64, json as _json
    payload = {{
        "raw_b64": _b64.b64encode(img.tobytes(order="C")).decode("ascii"),
        "shape": list(img.shape),
        "dtype": str(img.dtype),
        "meta": meta,
    }}
    print("{IMAGE_MARKER}" + _json.dumps(payload), flush=True)
'''


# Template for the default grid-imaging workflow.
DIGITAL_TWIN_TEMPLATE = '''"""
STEM Automation Script — generated by GridScope

Objective: {objective}

This script uses ONLY the portable MicroscopeControlClient: every call has a
real-instrument counterpart. The specimen is registered in the GridScope UI
before running. Stage soft limits and autofocus failures are handled.
"""

import time
from typing import Dict, List, Tuple

{control_client_code}

{report_image_helper}

# ========================================
# Configuration
# ========================================
CONFIG = {{
    "host": "127.0.0.1",
    "port": 9094,
    "field_of_view_um": {fov},
    "grid_rows": {grid_rows},
    "grid_cols": {grid_cols},
    "step_size_um": {step_size},
    "start_x_um": {start_x},
    "start_y_um": {start_y},
    "autofocus_enabled": {autofocus},
    "autofocus_z_range_um": 4.0,
    "autofocus_z_steps": 9,
    "dwell_time_s": {dwell_s},
}}


def calculate_tile_positions(start_x_um, start_y_um, step_size_um, rows, cols):
    """All tile positions in micrometers."""
    positions = []
    for row in range(rows):
        for col in range(cols):
            positions.append((row * cols + col,
                              start_x_um + col * step_size_um,
                              start_y_um + row * step_size_um))
    return positions


def run_experiment():
    """Run the automated grid imaging experiment."""
    mic = MicroscopeControlClient(host=CONFIG["host"], port=CONFIG["port"])

    ready = mic.is_ready()
    if not ready.get("ready"):
        print("ERROR: Microscope not ready:", ready.get("error"))
        return None
    if not ready.get("sample"):
        print("ERROR: No sample registered. Register one in Sample Settings.")
        return None
    print(f"Connected. Sample: {{ready['sample']}}")

    limits = mic.get_stage_limits()
    print(f"Stage soft limits: x/y ±{{limits['x']*1e3:.1f}} mm, "
          f"z ±{{limits['z']*1e3:.1f}} mm, tilt ±{{limits['a']:.0f}}°")

    mic.device_settings("haadf", field_of_view_um=CONFIG["field_of_view_um"])
    print(f"FOV set to {{CONFIG['field_of_view_um']}} µm "
          f"(mag {{mic.get_magnification()['magnification']/1e3:.1f}} kx)")

    positions = calculate_tile_positions(
        CONFIG["start_x_um"], CONFIG["start_y_um"], CONFIG["step_size_um"],
        CONFIG["grid_rows"], CONFIG["grid_cols"])
    total = len(positions)
    print(f"Acquiring {{total}} tiles...")

    acquired = 0
    for tile_index, x_um, y_um in positions:
        print(f"Tile {{tile_index + 1}}/{{total}}: X={{x_um:.2f}} µm, Y={{y_um:.2f}} µm")

        try:
            mic.set_stage({{"x": x_um * 1e-6, "y": y_um * 1e-6}}, relative=False)
        except RuntimeError as e:
            # Soft limit rejection: the stage did not move. Skip this tile.
            print(f"  SKIPPED — stage move rejected: {{e}}")
            continue

        if CONFIG["autofocus_enabled"]:
            af = mic.autofocus("haadf",
                               z_range_um=CONFIG["autofocus_z_range_um"],
                               z_steps=CONFIG["autofocus_z_steps"])
            if af["converged"]:
                print(f"  Autofocus: Z adjusted by {{af['best_z_um_relative']:.2f}} µm")
            else:
                print(f"  Autofocus did not converge ({{af['reason']}}); "
                      f"imaging at current focus")

        img = mic.acquire_image("haadf")
        acquired += 1
        report_image(img, tile=tile_index, x_um=x_um, y_um=y_um)
        print(f"  Acquired {{img.shape}} {{img.dtype}}")

        if CONFIG["dwell_time_s"] > 0:
            time.sleep(CONFIG["dwell_time_s"])

    print(f"Done: {{acquired}}/{{total}} tiles acquired.")
    return acquired


if __name__ == "__main__":
    run_experiment()
'''


# Connection bootstrap prepended to LLM-written code. LLM output uses `mic`
# directly (per the prompts); defining it here makes the script runnable even
# if the model forgets the instantiation.
CONNECTION_BOOTSTRAP = '''
# Connection to the microscope (digital twin now, vendor SDK later)
mic = MicroscopeControlClient(host="127.0.0.1", port=9094)
'''


def ensure_self_contained(code: str) -> str:
    """Prepend the control client + report helper + `mic` connection unless
    already present.

    Guarantees any generated script is runnable stand-alone and structurally
    limited to the portable control surface.
    """
    if "class MicroscopeControlClient" in code:
        return code
    return (CONTROL_CLIENT_CODE + "\n\n" + REPORT_IMAGE_HELPER + "\n"
            + CONNECTION_BOOTSTRAP + "\n" + code)


class MicroscopyCodeGenerator:
    """Generates Python automation code using the portable control client."""

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        if self.api_key:
            self.client = AsyncOpenAI(api_key=self.api_key)
        else:
            self.client = None
        self.model = os.getenv("OPENAI_MODEL", "gpt-4o")

    def _get_config_values(self, config: Optional[ExperimentConfig]) -> dict:
        """Extract configuration values with defaults."""
        if config:
            return {
                "fov": config.fov,
                "grid_rows": config.grid.rows,
                "grid_cols": config.grid.cols,
                "step_size": config.grid.step_size,
                "start_x": config.start_pos.x,
                "start_y": config.start_pos.y,
                "autofocus": str(config.autofocus_each_tile),
                "dwell_s": config.dwell_s,
            }
        return {
            "fov": 20,
            "grid_rows": 5,
            "grid_cols": 5,
            "step_size": 16.0,
            "start_x": 0,
            "start_y": 0,
            "autofocus": "True",
            "dwell_s": 0.5,
        }

    def generate_from_template(self, request: CodeGenerationRequest) -> str:
        """Generate code using the grid-imaging template."""
        values = self._get_config_values(request.experiment_config)
        values["objective"] = request.objective
        values["control_client_code"] = CONTROL_CLIENT_CODE
        values["report_image_helper"] = REPORT_IMAGE_HELPER
        return DIGITAL_TWIN_TEMPLATE.format(**values)

    async def generate_with_llm(self, request: CodeGenerationRequest) -> dict:
        """Generate code using LLM for custom requirements."""
        if not self.client:
            code = self.generate_from_template(request)
            return {
                "code": code,
                "explanation": "Generated using template (no API key configured)",
                "warnings": ["LLM enhancement unavailable"],
                "suggested_modifications": [],
            }

        config_context = ""
        if request.experiment_config:
            config = request.experiment_config
            config_context = f"""
Current Experiment Configuration:
- FOV: {config.fov} µm
- Grid: {config.grid.rows}x{config.grid.cols} tiles
- Step Size: {config.grid.step_size} µm
- Start Position: ({config.start_pos.x}, {config.start_pos.y}) µm
- Autofocus: {config.autofocus_each_tile}
- Dwell Time: {config.dwell_s}s
"""

        prompt = f"""Generate a Python script for the STEM microscope based on this request:

Objective: {request.objective}
{config_context}
Additional Requirements: {request.additional_requirements or 'None'}

{MICROSCOPE_API_SPEC}

Rules:
- Write code against MicroscopeControlClient ONLY. The class, a
  report_image(img, **meta) helper, AND a ready connection
  `mic = MicroscopeControlClient(host="127.0.0.1", port=9094)` are prepended
  to your code automatically — use `mic` directly; do NOT redefine or
  re-instantiate any of them.
- NEVER reference samples, environments, drift, damage, or contamination —
  the specimen is registered in the UI before the script runs.
- Stage positions in METRES (µm × 1e-6); tilt in DEGREES.
- Handle stage-limit rejections (RuntimeError from set_stage) and autofocus
  non-convergence (result["converged"] is False).
- Call report_image(img, ...) after every acquire_image.
- Always use "{DEFAULT_DETECTOR}" as the detector.

Respond with JSON:
{{
    "code": "python code WITHOUT the client class (it is prepended automatically)",
    "explanation": "what the code does",
    "warnings": ["safety notes"],
    "suggested_modifications": ["customization ideas"]
}}"""

        response = await self.client.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": "You are an expert microscopy automation programmer. "
                               "Generate clean Python using ONLY the portable "
                               "MicroscopeControlClient API. Respond with valid JSON.",
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
            max_tokens=4000,
        )

        import json
        try:
            result = json.loads(response.choices[0].message.content or "{}")
        except json.JSONDecodeError:
            result = {
                "code": response.choices[0].message.content or "",
                "explanation": "Generated code",
                "warnings": [],
                "suggested_modifications": [],
            }
        result["code"] = ensure_self_contained(result.get("code", ""))
        return result

    async def generate(self, request: CodeGenerationRequest) -> dict:
        """Generate microscopy automation code."""
        if self.client and request.additional_requirements:
            return await self.generate_with_llm(request)

        code = self.generate_from_template(request)
        return {
            "code": code,
            "explanation": f"Generated portable automation script for: {request.objective}",
            "warnings": [
                "Register a sample in Sample Settings before running",
                "Stage soft limits: ±1.5 mm (x/y), ±1 mm (z), ±30° (tilt) — "
                "out-of-range tiles are skipped",
            ],
            "suggested_modifications": [
                "Adjust field_of_view_um / magnification for the sample's feature scale",
                "Tune autofocus z_range_um and z_steps",
                "Add a tilt series or diffraction acquisition step",
            ],
        }
